function [fitresult_X, gof_X] = CCG_GaussFit_X(x, avg_ccg_x)
%CREATEFIT(X,AVG_CCG_X)
%  Create a fit.
%
%  Data for 'CCG_GaussFit_X' fit:
%      X Input : x
%      Y Output: avg_ccg_x
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 05-Sep-2019 19:46:42


%% Fit: 'CCG_GaussFit_X'.
[xData, yData] = prepareCurveData( x, avg_ccg_x );

% Set up fittype and options.
ft = fittype( 'gauss1' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.Lower = [-Inf -Inf 0];
opts.Normalize = 'on';
opts.StartPoint = [0.240027057877112 0.293777236063532 0.24954514342065];

% Fit model to data.
[fitresult_X, gof_X] = fit( xData, yData, ft, opts );

% Plot fit with data.
figure( 'Name', 'CCG_GaussFit_X' );
h = plot( fitresult_X, xData, yData );
legend( h, 'avg_ccg_x vs. x', 'CCG_GaussFit_X', 'Location', 'NorthEast', 'Interpreter', 'none' );
% Label axes
xlabel( 'x', 'Interpreter', 'none' );
ylabel( 'avg_ccg_x', 'Interpreter', 'none' );
grid on


